name: iosApp
options:
  bundleIdPrefix: app.xc.iosApp
targets:
  iosApp:
    type: application
    platform: iOS
    deploymentTarget: "15.2"
    sources: [ iosApp ]
    settings:
      DEVELOPMENT_TEAM: PMMM9GZU3K
    postBuildScripts:
      - script: |
          "$SRCROOT/../gradlew" -p "$SRCROOT/../" :shared:copyFrameworkResourcesToApp \
            -Pmoko.resources.BUILT_PRODUCTS_DIR="$BUILT_PRODUCTS_DIR" \
            -Pmoko.resources.CONTENTS_FOLDER_PATH="$CONTENTS_FOLDER_PATH" \
            -Pkotlin.native.cocoapods.platform="$PLATFORM_NAME" \
            -Pkotlin.native.cocoapods.archs="$ARCHS" \
            -Pkotlin.native.cocoapods.configuration="$CONFIGURATION"
        name: Copy moko res